// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThuVien.AppData;

namespace ThuVien.AppData.Migrations
{
    [DbContext(typeof(ThuVienConText))]
    [Migration("20191001091310_thuvien")]
    partial class thuvien
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThuVien.DoMain.KhoSach", b =>
                {
                    b.Property<string>("MaKho")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TenKho");

                    b.HasKey("MaKho");

                    b.ToTable("KhoSaches");
                });

            modelBuilder.Entity("ThuVien.DoMain.LoaiSach", b =>
                {
                    b.Property<string>("MaLoaiSach")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TenLoai");

                    b.HasKey("MaLoaiSach");

                    b.ToTable("LoaiSaches");
                });

            modelBuilder.Entity("ThuVien.DoMain.NgonNgu", b =>
                {
                    b.Property<string>("MaNgonNgu")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TenNgonNgu");

                    b.HasKey("MaNgonNgu");

                    b.ToTable("NgonNgus");
                });

            modelBuilder.Entity("ThuVien.DoMain.NhaXuatBan", b =>
                {
                    b.Property<string>("MaNXB")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DiaChi");

                    b.Property<string>("TenNXB");

                    b.HasKey("MaNXB");

                    b.ToTable("NhaXuatBans");
                });

            modelBuilder.Entity("ThuVien.DoMain.Sach", b =>
                {
                    b.Property<string>("MaSach")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MaKho");

                    b.Property<string>("MaLoaiSach");

                    b.Property<string>("MaNXB");

                    b.Property<string>("MaNgonNgu");

                    b.Property<string>("MaTG");

                    b.Property<string>("MaViTri");

                    b.Property<DateTime>("NamXuatBan");

                    b.Property<string>("SinhVienMaSv");

                    b.Property<int>("SoLuong");

                    b.Property<string>("TacGiaMaTacGia");

                    b.Property<string>("TenSach");

                    b.HasKey("MaSach");

                    b.HasIndex("MaKho");

                    b.HasIndex("MaLoaiSach");

                    b.HasIndex("MaNXB");

                    b.HasIndex("MaNgonNgu");

                    b.HasIndex("MaViTri");

                    b.HasIndex("SinhVienMaSv");

                    b.HasIndex("TacGiaMaTacGia");

                    b.ToTable("Saches");
                });

            modelBuilder.Entity("ThuVien.DoMain.SinhVien", b =>
                {
                    b.Property<string>("MaSv")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HoTen");

                    b.Property<string>("Lop");

                    b.HasKey("MaSv");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("ThuVien.DoMain.SinhVienMuonSach", b =>
                {
                    b.Property<string>("MaSach");

                    b.Property<string>("MaSv");

                    b.Property<string>("HinhThucMuon");

                    b.Property<DateTime>("NgayMuon");

                    b.Property<DateTime>("NgayTra");

                    b.Property<int>("SoNgayMuon");

                    b.HasKey("MaSach", "MaSv");

                    b.HasIndex("MaSv");

                    b.ToTable("SinhVienMuonSaches");
                });

            modelBuilder.Entity("ThuVien.DoMain.TacGia", b =>
                {
                    b.Property<string>("MaTacGia")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DiaChi");

                    b.Property<string>("TenTacGia");

                    b.HasKey("MaTacGia");

                    b.ToTable("TacGias");
                });

            modelBuilder.Entity("ThuVien.DoMain.ViTri", b =>
                {
                    b.Property<string>("MaViTri")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ke");

                    b.Property<string>("Khu");

                    b.Property<string>("Ngan");

                    b.HasKey("MaViTri");

                    b.ToTable("ViTris");
                });

            modelBuilder.Entity("ThuVien.DoMain.Sach", b =>
                {
                    b.HasOne("ThuVien.DoMain.KhoSach")
                        .WithMany("Saches")
                        .HasForeignKey("MaKho");

                    b.HasOne("ThuVien.DoMain.LoaiSach")
                        .WithMany("Saches")
                        .HasForeignKey("MaLoaiSach");

                    b.HasOne("ThuVien.DoMain.NhaXuatBan")
                        .WithMany("Saches")
                        .HasForeignKey("MaNXB");

                    b.HasOne("ThuVien.DoMain.NgonNgu")
                        .WithMany("Saches")
                        .HasForeignKey("MaNgonNgu");

                    b.HasOne("ThuVien.DoMain.ViTri")
                        .WithMany("Saches")
                        .HasForeignKey("MaViTri");

                    b.HasOne("ThuVien.DoMain.SinhVien")
                        .WithMany("Saches")
                        .HasForeignKey("SinhVienMaSv");

                    b.HasOne("ThuVien.DoMain.TacGia")
                        .WithMany("Saches")
                        .HasForeignKey("TacGiaMaTacGia");
                });

            modelBuilder.Entity("ThuVien.DoMain.SinhVienMuonSach", b =>
                {
                    b.HasOne("ThuVien.DoMain.Sach", "Sach")
                        .WithMany("SinhVienMuonSaches")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ThuVien.DoMain.SinhVien", "SinhVien")
                        .WithMany("SinhVienMuonSaches")
                        .HasForeignKey("MaSv")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
