// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WOTWebApp.Context;

namespace WOTWebApp.Migrations
{
    [DbContext(typeof(WotContext))]
    [Migration("20191003144617_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WOTWebApp.Models.Nation", b =>
                {
                    b.Property<int>("NationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NationName");

                    b.HasKey("NationId");

                    b.ToTable("Nations");
                });

            modelBuilder.Entity("WOTWebApp.Models.Tank", b =>
                {
                    b.Property<int>("TankId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Concealment");

                    b.Property<int>("FirePower");

                    b.Property<int>("Mobility");

                    b.Property<int>("NationId");

                    b.Property<int>("Spotting");

                    b.Property<int>("Survivability");

                    b.Property<string>("TankName");

                    b.Property<int>("TankTier");

                    b.Property<int>("TankTypeId");

                    b.HasKey("TankId");

                    b.HasIndex("NationId");

                    b.HasIndex("TankTypeId");

                    b.ToTable("Tanks");
                });

            modelBuilder.Entity("WOTWebApp.Models.TankType", b =>
                {
                    b.Property<int>("TankTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TankTypeName");

                    b.HasKey("TankTypeId");

                    b.ToTable("TankTypes");
                });

            modelBuilder.Entity("WOTWebApp.Models.Tank", b =>
                {
                    b.HasOne("WOTWebApp.Models.Nation", "Nation")
                        .WithMany("Tanks")
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WOTWebApp.Models.TankType", "TankType")
                        .WithMany("Tanks")
                        .HasForeignKey("TankTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
