// <auto-generated />
using BoDeTracNghiemDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoDeTracNghiemDemo.Migrations
{
    [DbContext(typeof(AppDataConText))]
    [Migration("20191021093928_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.CauHoi", b =>
                {
                    b.Property<int>("CauHoiId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CauTraLoi1")
                        .IsRequired();

                    b.Property<string>("CauTraLoi2")
                        .IsRequired();

                    b.Property<string>("CauTraLoi3")
                        .IsRequired();

                    b.Property<string>("CauTraLoi4")
                        .IsRequired();

                    b.Property<string>("TenCauHoi")
                        .IsRequired();

                    b.Property<int>("TheLoaiId");

                    b.HasKey("CauHoiId");

                    b.HasIndex("TheLoaiId");

                    b.ToTable("CauHois");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.CauHoiThi", b =>
                {
                    b.Property<int>("CauHoiId");

                    b.Property<int>("ThiId");

                    b.HasKey("CauHoiId", "ThiId");

                    b.HasIndex("ThiId");

                    b.ToTable("CauHoiThi");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.DapAn", b =>
                {
                    b.Property<int>("DapAnId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CauHoiId");

                    b.Property<string>("TenDapAn")
                        .IsRequired();

                    b.HasKey("DapAnId");

                    b.HasIndex("CauHoiId")
                        .IsUnique();

                    b.ToTable("DapAns");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.DiemThi", b =>
                {
                    b.Property<int>("DiemThiId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenDiemThi")
                        .IsRequired();

                    b.Property<int>("ThiId");

                    b.HasKey("DiemThiId");

                    b.HasIndex("ThiId")
                        .IsUnique();

                    b.ToTable("DiemThis");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("MatKau")
                        .IsRequired();

                    b.Property<string>("XacNhanMatKhau")
                        .IsRequired();

                    b.HasKey("NguoiDungId");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.TheLoai", b =>
                {
                    b.Property<int>("TheLoaiId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenTheLoai")
                        .IsRequired();

                    b.HasKey("TheLoaiId");

                    b.ToTable("TheLoais");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.Thi", b =>
                {
                    b.Property<int>("ThiId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NguoiDungId");

                    b.Property<string>("TenThi")
                        .IsRequired();

                    b.HasKey("ThiId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("Thi");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.CauHoi", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.TheLoai", "TheLoai")
                        .WithMany("CauHois")
                        .HasForeignKey("TheLoaiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.CauHoiThi", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.CauHoi", "CauHoi")
                        .WithMany("CauHoiThis")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BoDeTracNghiemDemo.Models.Thi", "Thi")
                        .WithMany("CauHoiThis")
                        .HasForeignKey("ThiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.DapAn", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.CauHoi", "CauHoi")
                        .WithOne("DapAn")
                        .HasForeignKey("BoDeTracNghiemDemo.Models.DapAn", "CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.DiemThi", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.Thi", "Thi")
                        .WithOne("DiemThi")
                        .HasForeignKey("BoDeTracNghiemDemo.Models.DiemThi", "ThiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.Thi", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.NguoiDung", "NguoiDung")
                        .WithMany("This")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
