// <auto-generated />
using System;
using BoDeTracNghiemDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoDeTracNghiemDemo.Migrations
{
    [DbContext(typeof(AppDataConText))]
    [Migration("20191021162825_Identity_user")]
    partial class Identity_user
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("City");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.CauHoi", b =>
                {
                    b.Property<int>("CauHoiId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CauTraLoi1")
                        .IsRequired();

                    b.Property<string>("CauTraLoi2")
                        .IsRequired();

                    b.Property<string>("CauTraLoi3")
                        .IsRequired();

                    b.Property<string>("CauTraLoi4")
                        .IsRequired();

                    b.Property<string>("TenCauHoi")
                        .IsRequired();

                    b.Property<int>("TheLoaiId");

                    b.HasKey("CauHoiId");

                    b.HasIndex("TheLoaiId");

                    b.ToTable("CauHois");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.CauHoiThi", b =>
                {
                    b.Property<int>("CauHoiId");

                    b.Property<int>("ThiId");

                    b.HasKey("CauHoiId", "ThiId");

                    b.HasIndex("ThiId");

                    b.ToTable("CauHoiThi");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.DapAn", b =>
                {
                    b.Property<int>("DapAnId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CauHoiId");

                    b.Property<string>("TenDapAn")
                        .IsRequired();

                    b.HasKey("DapAnId");

                    b.HasIndex("CauHoiId")
                        .IsUnique();

                    b.ToTable("DapAns");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.DiemThi", b =>
                {
                    b.Property<int>("DiemThiId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenDiemThi")
                        .IsRequired();

                    b.Property<int>("ThiId");

                    b.HasKey("DiemThiId");

                    b.HasIndex("ThiId")
                        .IsUnique();

                    b.ToTable("DiemThis");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("MatKau")
                        .IsRequired();

                    b.Property<string>("PhotoPath");

                    b.Property<string>("XacNhanMatKhau")
                        .IsRequired();

                    b.HasKey("NguoiDungId");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.TheLoai", b =>
                {
                    b.Property<int>("TheLoaiId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenTheLoai")
                        .IsRequired();

                    b.HasKey("TheLoaiId");

                    b.ToTable("TheLoais");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.Thi", b =>
                {
                    b.Property<int>("ThiId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NguoiDungId");

                    b.Property<string>("TenThi")
                        .IsRequired();

                    b.HasKey("ThiId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("Thi");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.CauHoi", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.TheLoai", "TheLoai")
                        .WithMany("CauHois")
                        .HasForeignKey("TheLoaiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.CauHoiThi", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.CauHoi", "CauHoi")
                        .WithMany("CauHoiThis")
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BoDeTracNghiemDemo.Models.Thi", "Thi")
                        .WithMany("CauHoiThis")
                        .HasForeignKey("ThiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.DapAn", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.CauHoi", "CauHoi")
                        .WithOne("DapAn")
                        .HasForeignKey("BoDeTracNghiemDemo.Models.DapAn", "CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.DiemThi", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.Thi", "Thi")
                        .WithOne("DiemThi")
                        .HasForeignKey("BoDeTracNghiemDemo.Models.DiemThi", "ThiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BoDeTracNghiemDemo.Models.Thi", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.NguoiDung", "NguoiDung")
                        .WithMany("This")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BoDeTracNghiemDemo.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BoDeTracNghiemDemo.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
